# pairs of (input, expected output) or a single string 'SECTION NAME'
tests = [ 'Simple fractions',
  ('a = b/c', '\\text{a} = \\frac{\\text{b}}{\\text{c}}'),
  'Nested fractions',
  ('a / b / c', '\\frac{\\text{a}}{\\text{b} \\cdot \\text{c}}'),
  ( 'a / b / c / d',
    '\\frac{\\text{a}}{\\text{b} \\cdot \\text{c} \\cdot \\text{d}}'),
  ( 'a*b/c/d',
    '\\frac{\\text{a} \\cdot \\text{b}}{\\text{c} \\cdot \\text{d}}'),
  ( 'a*b/c*d/e',
    '\\frac{\\text{a} \\cdot \\text{b} \\cdot \\text{d}}{\\text{c} \\cdot \\text{e}}'),
  ( 'a*b/(c*d)',
    '\\frac{\\text{a} \\cdot \\text{b}}{\\text{c} \\cdot \\text{d}}'),
  ( '(a + b*c + d/e)/(g/h)',
    '\\frac{\\text{a} + \\text{b} \\cdot \\text{c} + \\frac{\\text{d}}{\\text{e}}}{\\frac{\\text{g}}{\\text{h}}}'),
  ( 'a + b/c + d/e/g*h',
    '\\text{a} + \\frac{\\text{b}}{\\text{c}} + \\frac{\\text{d} \\cdot \\text{h}}{\\text{e} \\cdot \\text{g}}'),
  'Element-wise (dot) notation',
  ( 'a.*b/c./d',
    '\\frac{\\text{a} \\cdot \\text{b}}{\\text{c} \\cdot \\text{d}}'),
  'Function calls',
  ( 'brHeight(a + b/c) + b/c + d/e/g*h',
    '\\text{brHeight} \\left( \\text{a} + \\frac{\\text{b}}{\\text{c}} \\right) + \\frac{\\text{b}}{\\text{c}} + \\frac{\\text{d} \\cdot \\text{h}}{\\text{e} \\cdot \\text{g}}'),
  'Unary minus',
  ('-a*b', '\\text{-}\\text{a} \\cdot \\text{b}'),
  ('-(a*b)', '\\text{-} \\left( \\text{a} \\cdot \\text{b} \\right)'),
  ('-a/b', '\\frac{\\text{-}\\text{a}}{\\text{b}}'),
  ( '-a*-(b/c+d)',
    '\\text{-}\\text{a} \\cdot \\text{-} \\left( \\frac{\\text{b}}{\\text{c}} + \\text{d} \\right)'),
  'Unary negation',
  ('~x', '\\sim\\text{x}'),
  ('~~~x/y', '\\frac{\\sim\\sim\\sim\\text{x}}{\\text{y}}'),
  ('~~~(x/y)', '\\sim\\sim\\sim\\frac{\\text{x}}{\\text{y}}'),
  'Special array access',
  ('arr{5/3}', '\\text{arr} \\left \\{ \\frac{5}{3} \\right \\}'),
  ( 'hello{world/3}',
    '\\text{hello} \\left \\{ \\frac{\\text{world}}{3} \\right \\}'),
  ('arr[5/3]', '\\text{arr} \\left[ \\frac{5}{3} \\right]'),
  ( 'arr[x{y}]',
    '\\text{arr} \\left[ \\text{x} \\left \\{ \\text{y} \\right \\} \\right]'),
  'Struct access',
  ('foo.bar / 4', '\\frac{\\text{foo.bar}}{4}'),
  'R data frame access',
  ('foo$bar / 4', '\\frac{\\text{foo\\$bar}}{4}'),
  'Underscores',
  ('my_big_variable_name', '\\text{my\\_big\\_variable\\_name}'),
  'Colons and commas inside of array operations',
  ('matrix1(3,4)/8', '\\frac{\\text{matrix1} \\left( 3 , 4 \\right)}{8}'),
  ('arr(3:5)', '\\text{arr} \\left( 3 : 5 \\right)'),
  ('arr(3:5:xyz)', '\\text{arr} \\left( 3 : 5 : \\text{xyz} \\right)'),
  ( 'arr(3:5/23:xyz)',
    '\\text{arr} \\left( 3 : \\frac{5}{23} : \\text{xyz} \\right)'),
  ('arr(:)', '\\text{arr} \\left( : \\right)'),
  ('4*a(3,:)', '4 \\cdot \\text{a} \\left( 3 , : \\right)'),
  ('4*a(6/2,:)', '4 \\cdot \\text{a} \\left( \\frac{6}{2} , : \\right)'),
  ( 'A(i,j,k,:)',
    '\\text{A} \\left( \\text{i} , \\text{j} , \\text{k} , : \\right)'),
  ('A(:,:)', '\\text{A} \\left( : , : \\right)'),
  ('A{:,:}', '\\text{A} \\left \\{ : , : \\right \\}'),
  ('a(-2,:)', '\\text{a} \\left( \\text{-}2 , : \\right)'),
  'Exponents',
  ('5^kevin', '5^{ \\text{kevin} }'),
  ('5.^kevin', '5^{ \\text{kevin} }'),
  ('2^3*5', '2^{ 3 } \\cdot 5'),
  ('3/5^y', '\\frac{3}{5^{ \\text{y} }}'),
  ('3./5^y', '\\frac{3}{5^{ \\text{y} }}'),
  ('a*b^(4/7)', '\\text{a} \\cdot \\text{b}^{ \\frac{4}{7} }'),
  ( 'sqrt((w/c)^2 - (n*pi/d)^2)',
    '\\sqrt{ \\left( \\frac{\\text{w}}{\\text{c}} \\right)^{ 2 } -  \\left( \\frac{\\text{n} \\cdot \\pi}{\\text{d}} \\right)^{ 2 }}'),
  'Square roots',
  ('sqrt(3/5)', '\\sqrt{\\frac{3}{5}}'),
  ( 'sqrt(a + 3/(x+y))',
    '\\sqrt{\\text{a} + \\frac{3}{\\text{x} + \\text{y}}}'),
  "Kevin's real-world examples",
  ( 'mu_h*((1-phi)/(1+2/3*phi))',
    '\\text{mu\\_h} \\cdot \\frac{1 - \\text{phi}}{1 + \\frac{2 \\cdot \\text{phi}}{3}}'),
  ( '(1./(sqrt(-1)*2*pi*freqs(k)*rhos)).*dpdr(:,k)',
    '\\frac{1}{\\sqrt{\\text{-}1} \\cdot 2 \\cdot \\pi \\cdot \\text{freqs} \\left( \\text{k} \\right) \\cdot \\text{rhos}} \\cdot \\text{dpdr} \\left( : , \\text{k} \\right)'),
  ( 'trapz(int_recreated_long{i_freq}, z_pos_long{i_freq})',
    '\\text{trapz} \\left( \\text{int\\_recreated\\_long} \\left \\{ \\text{i\\_freq} \\right \\} , \\text{z\\_pos\\_long} \\left \\{ \\text{i\\_freq} \\right \\} \\right)'),
  ( '(-1./(sqrt(-1)*2*pi*freqs(i_freq)*env_rhos{i_freq})).*(TmpP2(:,i_freq) - TmpP(:,i_freq))/dr_1;',
    '\\frac{\\text{-}1}{\\sqrt{\\text{-}1} \\cdot 2 \\cdot \\pi \\cdot \\text{freqs} \\left( \\text{i\\_freq} \\right) \\cdot \\text{env\\_rhos} \\left \\{ \\text{i\\_freq} \\right \\}} \\cdot \\frac{\\text{TmpP2} \\left( : , \\text{i\\_freq} \\right) - \\text{TmpP} \\left( : , \\text{i\\_freq} \\right)}{\\text{dr\\_1}}'),
  ( 'beta = 1 / (sqrt(1-(v/c)^2))',
    '\\text{beta} = \\frac{1}{\\sqrt{1 -  \\left( \\frac{\\text{v}}{\\text{c}} \\right)^{ 2 }}}'),
  'Butt-kickers for nested fractions',
  ( 'a*b/c*d*e/f/g/h',
    '\\frac{\\text{a} \\cdot \\text{b} \\cdot \\text{d} \\cdot \\text{e}}{\\text{c} \\cdot \\text{f} \\cdot \\text{g} \\cdot \\text{h}}'),
  'Redundant parens',
  ('(((a + b)))', ' \\left( \\text{a} + \\text{b} \\right)'),
  ('x / (y * z)', '\\frac{\\text{x}}{\\text{y} \\cdot \\text{z}}'),
  ('x + (y / z)', '\\text{x} + \\frac{\\text{y}}{\\text{z}}'),
  ('x ^ (y / z)', '\\text{x}^{ \\frac{\\text{y}}{\\text{z}} }'),
  ('(x ^ y) + z', '\\text{x}^{ \\text{y} } + \\text{z}'),
  ( '((x + y)) ^ (((z + w)))',
    ' \\left(  \\left( \\text{x} + \\text{y} \\right) \\right)^{ \\text{z} + \\text{w} }'),
  ( '((x + y)) / (((z + w)))',
    '\\frac{\\text{x} + \\text{y}}{\\text{z} + \\text{w}}'),
  ( '(1 + 2) / 3 ^ ((((((4 + 5)) * 6))))',
    '\\frac{1 + 2}{3^{  \\left( 4 + 5 \\right) \\cdot 6 }}'),
  'Multiplications',
  ('4 * x', '4 \\cdot \\text{x}'),
  ('x * 4', '\\text{x} \\cdot 4'),
  'Left divide',
  ('6 \\ 5', '\\frac{5}{6}'),
  ('a \\ (b / c)', '\\frac{\\frac{\\text{b}}{\\text{c}}}{\\text{a}}'),
  'Transpose',
  ("A'", '\\text{A}^{H}'),
  ("A.'", '\\text{A}^{T}'),
  'Ignoring trailing semi-colons',
  ('x = y + z;', '\\text{x} = \\text{y} + \\text{z}'),
  ('x + 5; \n\n', '\\text{x} + 5'),
  'Pi',
  ('pi * r ^2', '\\pi \\cdot \\text{r}^{ 2 }'),
  ('pi / 2', '\\frac{\\pi}{2}'),
  'Comparisons',
  ('a < b / c', '\\text{a} < \\frac{\\text{b}}{\\text{c}}'),
  ('a <= b / c', '\\text{a} \\leq \\frac{\\text{b}}{\\text{c}}'),
  ('a > b / c', '\\text{a} > \\frac{\\text{b}}{\\text{c}}'),
  ('a >= b / c', '\\text{a} \\geq \\frac{\\text{b}}{\\text{c}}'),
  ('a == b / c', '\\text{a} == \\frac{\\text{b}}{\\text{c}}'),
  ('a ~= b / c', '\\text{a} \\neq \\frac{\\text{b}}{\\text{c}}'),
  ('a != b / c', '\\text{a} \\neq \\frac{\\text{b}}{\\text{c}}'),
  'AndOr',
  ('a & b', '\\text{a} \\& \\text{b}'),
  ('a | b', '\\text{a} | \\text{b}'),
  ('a && b', '\\text{a} \\&\\& \\text{b}'),
  ('a || b', '\\text{a} || \\text{b}'),
  ( 'a & b / (c || d)',
    '\\text{a} \\& \\frac{\\text{b}}{\\text{c} || \\text{d}}'),
  'Stand-alone colon',
  ('a:b', '\\text{a} : \\text{b}'),
  ('1+2:3/4', '1 + 2 : \\frac{3}{4}'),
  'Render fractions as siblings',
  ( '(a + b)/(c + d)/(f*g)*(h + i)',
    '\\frac{\\text{a} + \\text{b}}{ \\left( \\text{c} + \\text{d} \\right) \\cdot  \\left( \\text{f} \\cdot \\text{g} \\right)} \\cdot  \\left( \\text{h} + \\text{i} \\right)'),
  ( '2*a/b*c*(sin(pi*c/2)/(pi*c)/2 )',
    '\\frac{2 \\cdot \\text{a} \\cdot \\text{c}}{\\text{b}} \\cdot \\frac{\\text{sin} \\left( \\frac{\\pi \\cdot \\text{c}}{2} \\right)}{ \\left( \\pi \\cdot \\text{c} \\right) \\cdot 2}'),
  ( '1/2*(real(pressure_recreated1{i_freq}.*conj(vr_recreated{i_freq})))',
    '\\frac{1}{2} \\cdot  \\left( \\text{real} \\left( \\text{pressure\\_recreated1} \\left \\{ \\text{i\\_freq} \\right \\} \\cdot \\text{conj} \\left( \\text{vr\\_recreated} \\left \\{ \\text{i\\_freq} \\right \\} \\right) \\right) \\right)'),
  'stand-alone brackets',
  ('[3:5]', ' \\left[ 3 : 5 \\right]'),
  ('[x+y : z]', ' \\left[ \\text{x} + \\text{y} : \\text{z} \\right]'),
  ( '[x+y : z/w]',
    ' \\left[ \\text{x} + \\text{y} : \\frac{\\text{z}}{\\text{w}} \\right]')]
